// Shared types for the in-browser Proof Kit demo — the TypeScript port of the
// k3s reference kit's pipeline (sensor-simulator → gateway → edge-inference).
// The Python originals live in
// reference-kits/semiconductor-predictive-maintenance/demo/images/; parity is
// enforced by tests/demo/golden-parity.test.ts against fixtures generated by
// scripts/generate-golden-vectors.py from the REAL Python model.

/** One telemetry frame: sensor name → reading. Mirrors the MQTT payload's
 * `sensors` object on `fab-devices/<tool>/raw`. */
export type SensorFrame = Record<string, number>;

export type ToolState = "HEALTHY" | "WATCH" | "WARNING" | "CRITICAL";

export type Contributor = { sensor: string; z: number };

/** The model's per-frame output — same shape the Python service publishes on
 * `fab/<tool>/health` and serves from /api/health. */
export type Verdict = {
  tool_id: string;
  frames: number;
  warming: boolean;
  health: number;
  state: ToolState;
  anomaly: number;
  rul_frames: number | null;
  top_contributors: Contributor[];
};

export type FaultName = "rf_match_drift" | "he_seal_leak" | "chiller_fault";

/** Gateway (Losant GEA tier) counters — mirrors gateway.py's `stats` dict.
 * In the browser demo the "edge box" is the visitor's tab: raw telemetry is
 * structurally incapable of leaving it, which is the same governance story the
 * k3s kit proves with NetworkPolicy + topic separation. */
export type GatewayStats = {
  raw_ingested: number;
  normalized_published: number;
  derived_seen: number;
  losant_forwarded: number;
  losant_withheld_airgapped: number;
  losant_connected: boolean;
  site: string;
  line: string;
};

export type HistorySample = {
  ts: number;
  health: number;
  state: ToolState;
  sensors: SensorFrame;
};

/** Fleet snapshot — same shape as the Python service's GET /api/health. */
export type FleetSnapshot = {
  frames_processed: number;
  uptime_s: number;
  counts: Partial<Record<ToolState, number>>;
  tools: Verdict[];
  sensors: string[];
};
