/**
 * Golden parity: the TypeScript health model vs. the REAL Python model.
 *
 * tests/demo/golden-vectors.json is generated by
 * scripts/generate-golden-vectors.py, which drives the actual Python model +
 * simulator drift tables from the k3s reference kit and records every input
 * frame and output verdict (590 steps across 6 scenarios: healthy, all three
 * fault signatures, a missing sensor channel, a constant/zero-variance
 * channel). This suite replays those exact frames through the TS port and
 * compares every field of every verdict.
 *
 * Parity bar (deliberate, documented): tolerance-based, not bit-exact.
 * Both runtimes are IEEE-754 doubles and the arithmetic is ported in the same
 * order, but transcendentals (exp/log) are not guaranteed identical between
 * libm and V8, and Python's round() is correctly-rounded-decimal banker's
 * rounding while the port scales-then-rounds. Observed differences are ~1e-12
 * relative; the tolerances below are far above that noise floor and far below
 * anything a dashboard (or an engineer) could distinguish. RNG stream parity
 * is explicitly NOT claimed — the vectors carry Python-recorded frames, and
 * the TS simulator is separately tested as statistically equivalent.
 */
import { describe, expect, it } from "vitest";
import golden from "./golden-vectors.json";
import {
  SENSORS,
  ToolHealthModel,
  classify,
} from "@/lib/demo/health-model";
import { BASE, FAULTS } from "@/lib/demo/simulator";
import type { SensorFrame, ToolState } from "@/lib/demo/types";

type GoldenVerdict = {
  tool_id: string;
  frames: number;
  warming: boolean;
  health: number;
  state: ToolState;
  anomaly: number;
  rul_frames: number | null;
  top_contributors: Array<{ sensor: string; z: number }>;
};
type GoldenStep = { frame: SensorFrame; verdict: GoldenVerdict };
type GoldenScenario = {
  name: string;
  fault: string | null;
  warmup: number;
  steps: GoldenStep[];
};

const HEALTH_TOL = 0.011; // both sides round to 2 decimals
const ANOMALY_TOL = 2e-4; // both sides round to 4 decimals
const Z_TOL = 0.011;
const STATE_BANDS = [85.0, 65.0, 40.0];

const scenarios = golden.scenarios as GoldenScenario[];

describe("single source of truth: constants match the Python kit", () => {
  it("sensor contract matches", () => {
    expect([...SENSORS]).toEqual(golden.sensors);
  });

  it("simulator healthy operating point (BASE) matches", () => {
    expect(Object.fromEntries(Object.entries(BASE))).toEqual(golden.base);
  });

  it("fault library (FAULTS) matches", () => {
    expect(FAULTS).toEqual(golden.faults);
  });
});

describe("state bands classify like the Python model", () => {
  it("maps representative healths to the same states", () => {
    expect(classify(100)).toBe("HEALTHY");
    expect(classify(85)).toBe("HEALTHY");
    expect(classify(84.99)).toBe("WATCH");
    expect(classify(65)).toBe("WATCH");
    expect(classify(64.99)).toBe("WARNING");
    expect(classify(40)).toBe("WARNING");
    expect(classify(39.99)).toBe("CRITICAL");
    expect(classify(0)).toBe("CRITICAL");
  });
});

function nearBandEdge(health: number): boolean {
  return STATE_BANDS.some((b) => Math.abs(health - b) <= 2 * HEALTH_TOL);
}

describe.each(scenarios.map((s) => [s.name, s] as const))(
  "golden parity — scenario %s",
  (_name, scenario) => {
    it(`matches all ${scenario.steps.length} Python verdicts`, () => {
      const model = new ToolHealthModel("etch-01", scenario.warmup);
      for (const [i, step] of scenario.steps.entries()) {
        const got = model.update(step.frame);
        const want = step.verdict;
        const at = `step ${i + 1}/${scenario.steps.length}`;

        expect(got.frames, at).toBe(want.frames);
        expect(got.warming, at).toBe(want.warming);
        expect(Math.abs(got.health - want.health), `${at} health ${got.health} vs ${want.health}`).toBeLessThanOrEqual(HEALTH_TOL);
        expect(Math.abs(got.anomaly - want.anomaly), `${at} anomaly ${got.anomaly} vs ${want.anomaly}`).toBeLessThanOrEqual(ANOMALY_TOL);

        // State must match exactly unless health sits on a band edge, where a
        // sub-tolerance float difference can legitimately flip it.
        if (!nearBandEdge(want.health)) {
          expect(got.state, `${at} state (health ${got.health})`).toBe(want.state);
        }

        // RUL: null must match null; numeric within ±1 frame (int rounding of
        // a shared least-squares forecast).
        if (want.rul_frames === null) {
          expect(got.rul_frames, `${at} rul`).toBeNull();
        } else {
          expect(got.rul_frames, `${at} rul`).not.toBeNull();
          expect(Math.abs((got.rul_frames as number) - want.rul_frames), `${at} rul ${got.rul_frames} vs ${want.rul_frames}`).toBeLessThanOrEqual(1);
        }

        // Sensor attribution: same sensors (order can swap only on abs-z
        // ties), z values within display tolerance.
        const gotBy = new Map(got.top_contributors.map((c) => [c.sensor, c.z]));
        const wantBy = new Map(want.top_contributors.map((c) => [c.sensor, c.z]));
        expect([...gotBy.keys()].sort(), `${at} contributor sensors`).toEqual(
          [...wantBy.keys()].sort(),
        );
        for (const [sensor, z] of wantBy) {
          expect(Math.abs((gotBy.get(sensor) as number) - z), `${at} z(${sensor})`).toBeLessThanOrEqual(Z_TOL);
        }
      }
    });
  },
);

describe("golden scenarios reach the outcomes the kit demos live", () => {
  it("every fault signature drives the TS model to CRITICAL with a RUL", () => {
    for (const scenario of scenarios.filter((s) => s.fault)) {
      const model = new ToolHealthModel("etch-01", scenario.warmup);
      let last;
      for (const step of scenario.steps) last = model.update(step.frame);
      expect(last!.state, scenario.name).toBe("CRITICAL");
      expect(last!.rul_frames, scenario.name).not.toBeNull();
      expect(last!.top_contributors.length, scenario.name).toBeGreaterThan(0);
    }
  });

  it("the dominant attributed sensor is one the fault actually drifts", () => {
    for (const scenario of scenarios.filter((s) => s.fault)) {
      const model = new ToolHealthModel("etch-01", scenario.warmup);
      let last;
      for (const step of scenario.steps) last = model.update(step.frame);
      const drifted = Object.keys(
        golden.faults[scenario.fault as keyof typeof golden.faults],
      );
      expect(drifted, scenario.name).toContain(last!.top_contributors[0].sensor);
    }
  });
});
