-- GENERATED FILE — do not edit by hand.
-- Source: supabase/seed-data.ts. Regenerate with `npm run db:seed:generate`.

truncate table
  proof_kits, component_map_rows, scale_up_stages, footprint_specs,
  ledger_phases, open_threads
  restart identity cascade;

insert into proof_kits (slug, name, partner, customer, industry, use_case, status, summary, demo_path, repo_url) values
  ('semiconductor-predictive-maintenance', 'Semiconductor predictive maintenance — edge AI', 'Technologent', 'Microchip Technology', 'Semiconductor manufacturing', 'OT telemetry -> Losant Gateway Edge Agent -> on-prem inference (health score + RUL + sensor attribution) -> ops dashboard, with raw telemetry held inside the fab and only derived scores allowed to leave.', 'built-and-verified', 'The fully-worked reference Proof Kit: a runnable minimal-footprint MVP plus the partner hand-off. Losant (SUSE Industrial Edge) is a first-class tier of the running demo, and Rancher is wired via an MCP server with live Fleet GitOps.', 'reference-kits/semiconductor-predictive-maintenance/demo', 'https://github.com/MetalRoosterSimulation/edge-proof-factory');

insert into component_map_rows (kit_slug, demo_component, role, production_component, pinned_version, sort_order) values
  ('semiconductor-predictive-maintenance', 'sensor-simulator', 'Stands in for PLC / OPC UA / Modbus device outputs', 'The fab''s real equipment + protocol adapters', 'n/a (customer OT)', 0),
  ('semiconductor-predictive-maintenance', 'mosquitto + gateway-edge-agent (runs the real losant-mqtt SDK)', 'Local broker, normalize, offline-buffer, governed egress', 'SUSE Industrial Edge — Losant Gateway Edge Agent (losant/edge-agent) running an Edge Workflow', 'Losant GEA (SUSE OEM)', 1),
  ('semiconductor-predictive-maintenance', 'k3d (k3s in Docker), single node', 'Edge Kubernetes', 'SUSE Edge: K3s on SUSE Linux Micro; RKE2 where CIS/FIPS is required', 'SL Micro 6.2 - K3s 1.35.3 - RKE2 1.35.3', 2),
  ('semiconductor-predictive-maintenance', '(manual node)', 'Immutable edge OS', 'SUSE Linux Micro (read-only Btrfs, A/B, SELinux)', '6.2', 3),
  ('semiconductor-predictive-maintenance', '(n/a in demo)', 'Remote onboarding / phone-home', 'Elemental (+ Edge Image Builder to bake the boot image)', 'Elemental 1.9.0 - EIB 1.3.3.1', 4),
  ('semiconductor-predictive-maintenance', 'edge-inference (CPU control-chart model)', 'On-prem health scoring + RUL', 'SUSE AI: Ollama/vLLM + Milvus (+ heavier model), on a GPU node', 'SUSE AI 1.0', 5),
  ('semiconductor-predictive-maintenance', 'ollama + open-webui (open images)', 'Local GenAI assistant', 'SUSE AI — the identical Ollama + Open WebUI, from the SUSE Application Collection (dp.apps.rancher.io)', 'SUSE AI 1.0', 6),
  ('semiconductor-predictive-maintenance', 'kubectl / kustomize', 'Deploy', 'Rancher Prime + Fleet GitOps', 'Rancher Prime 2.14.1', 7),
  ('semiconductor-predictive-maintenance', 'NetworkPolicy (k3s default)', 'Runtime security', 'SUSE Security (NeuVector) — inline L7 enforcement; All-in-One for single node', 'NeuVector 5.5.1', 8),
  ('semiconductor-predictive-maintenance', 'emptyDir / k3s local-path', 'Storage', 'Single node: local-path (bundled). Multi-node: SUSE Storage (Longhorn)', 'Longhorn 1.11.1', 9);

insert into scale_up_stages (kit_slug, stage_number, title, body_md, sort_order) values
  ('semiconductor-predictive-maintenance', 0, 'The laptop demo (this kit)', 'Single-node k3s (k3d), all-open images, CPU only. Proves the pattern end to end. [P] Run `make up`; walk the customer through a live fault + the governance boundary — no customer hardware, no entitlement, no fab access needed. Exit: the customer agrees the pattern fits a named tool/zone.', 0),
  ('semiconductor-predictive-maintenance', 1, 'One real edge box (PILOT)', 'Move the same workloads onto one physical edge node in one fab zone. [P] Build a SUSE Edge boot image with Edge Image Builder (SL Micro 6.2 + K3s single-server + the kit''s manifests, air-gapped). [P] Deploy the Losant Gateway Edge Agent against the zone''s real OPC UA / Modbus feeds. [P/S] Stand up the inference tier — size the GPU here, not before, if SUSE AI is needed. [P] Add SUSE Security (NeuVector) All-in-One. [C] Provide the edge node and OT network path. Exit: real sensor data scored on real hardware; offline buffering and the governance boundary verified with the customer''s security team.', 1),
  ('semiconductor-predictive-maintenance', 2, 'Production hardening, one zone (ROLL OUT)', '[P] Decide HA now — rebuild on K3s embedded-etcd (3 nodes) or RKE2 with SUSE Storage (Longhorn) if the zone needs it; the datastore is baked into the image and cannot be a config flip later. [P] Stand up Rancher Prime as the management cluster; import the edge cluster (downstream agents dial out, no inbound firewall rule to the fab). [P] Put the kit manifests in Git; deploy via Fleet. Exit: the zone runs on the SUSE-supported stack, fleet-managed, GitOps-driven.', 2),
  ('semiconductor-predictive-maintenance', 3, 'Scale to the fab / many sites (DAY 2 & SCALE)', '[P] Onboard new nodes/zones with Elemental phone-home — no per-site hands-on. [P] Roll the same Fleet GitRepo to a ClusterGroup; new sites converge automatically (renewal grows per site, not just per year). [P] Day-2: Upgrade Controller for staged OS + K8s upgrades; Losant cross-site dashboards. [S] Deal-registration and support wrap across the fleet. Exit: steady-state managed fleet; each new tool/zone is a repeatable unit.', 3);

insert into footprint_specs (kit_slug, component, minimum_spec, sort_order) values
  ('semiconductor-predictive-maintenance', 'SUSE Linux Micro', '1 GB RAM / 20 GB disk (32 GB qcow2), UEFI only', 0),
  ('semiconductor-predictive-maintenance', 'K3s server', '2 CPU / 2 GB (single-server = SQLite, no HA)', 1),
  ('semiconductor-predictive-maintenance', 'K3s agent', '1 CPU / 512 MB', 2),
  ('semiconductor-predictive-maintenance', 'RKE2', '2 vCPU / 4 GB (~225 agents), SSD for etcd', 3),
  ('semiconductor-predictive-maintenance', 'Edge Image Builder (build host)', '4 GB RAM (8 GB rec.), --privileged', 4),
  ('semiconductor-predictive-maintenance', 'Elemental-onboarded node', 'TPM 2.0, UEFI x86-64, 25 GB volume', 5),
  ('semiconductor-predictive-maintenance', 'Rancher Prime mgmt (Small)', '4 vCPU / 16 GB per node, >=3 nodes for HA', 6),
  ('semiconductor-predictive-maintenance', 'SUSE AI (Basic, per node)', '4 cores / 32 GB / 50 GB SSD', 7),
  ('semiconductor-predictive-maintenance', 'Ollama (real inference)', 'NVIDIA GPU, 16 GB+ RAM, CUDA 11.0+', 8),
  ('semiconductor-predictive-maintenance', 'SUSE Security (NeuVector)', '2 cores / 2 GB / 5 GB + RWX 1-5 Gi', 9),
  ('semiconductor-predictive-maintenance', 'SUSE Storage (Longhorn)', '3 nodes, 4 vCPU / 4 GiB per node (multi-node only)', 10);

insert into ledger_phases (phase_number, title, status, body_md, done_date) values
  (0, 'Research swarm', 'done', 'Four agents read the two sibling factories, the shared suse-brain.md (Edge/AI product facts + version matrix), and the partner motion/economics. Confirmed the gap: both factories produce paper; no runnable MVP or hand-off existed anywhere in ~/Work. Semiconductor predictive-maintenance chosen as the reference use case (Technologent / Microchip Technology).', null),
  (1, 'The runnable MVP (reference kit)', 'done', 'Stood up a real single-node k3s cluster (k3d, v1.35.5). Built the edge-inference model (EWMA-smoothed multivariate control chart, Hotelling T^2 / Mahalanobis SPC, frozen Welford baseline, health score + trend-extrapolated RUL + sensor attribution — pure Python/stdlib, 9/9 unit tests, CPU-only), the sensor-simulator (synthetic plasma-etch telemetry with three fault signatures), and a self-contained ops dashboard. Verified end to end live: healthy fleet reads 6x100; injected fault degrades WATCH -> WARNING -> CRITICAL with RUL counting to 0 and correct sensor attribution.', null),
  (2, 'Losant / SUSE Industrial Edge as a first-class tier', 'done', 'Inserted a gateway-edge-agent (Losant GEA) tier as the single governed egress point: raw OT telemetry -> normalize + offline-buffer -> inference -> derived health -> gateway forwards only derived scores to Losant via the real losant-mqtt SDK. Raw telemetry structurally cannot leave. Verified live: gateway withheld 100% of raw frames in air-gapped mode.', null),
  (3, 'SUSE AI profile', 'done', '`make ai` adds Ollama + Open WebUI (real Application Collection components) and an on-prem /api/explain/<tool> endpoint with a graceful fallback when the AI tier is off. Optional profile — the base kit stays CPU/laptop-class.', null),
  (4, 'Rancher MCP server', 'done', 'Built integrations/rancher-mcp-server/ — a Node/stdio MCP server with 10 tools (list clusters/nodes/projects/namespaces/workloads/fleet, deploy-via-Fleet, import-cluster). Mock mode for offline testing; selftest green on the full stdio handshake.', null),
  (5, 'Hand-off kit + factory scaffolding', 'done', 'Wrote the hand-off kit (00 runbook, 01 component map, 02 scale-up path, 03 production footprint) and the reusable factory machine: START-HERE, CLAUDE.md, RUN.md, docs (project-brief, suse-edge-ai-stack, handoff-doctrine, footprint-rules), templates, and tools/validate_kit.py. Verification: model unit tests 9/9, validate_kit.py 15 pass / 0 warn / 0 fail, Rancher MCP selftest all pass, cold make up end-to-end with live fault + governance proof.', null),
  (6, 'Live Rancher wiring', 'done', 'Connected to a local Rancher Community v2.13.3 instance. Debugged two 401''ing tokens (missing token- prefix); the client and wire-rancher.sh now auto-add the prefix. Imported the k3d edge-mvp cluster into Rancher; verified via the MCP server in real mode that rancher_list_clusters shows edge-mvp active and rancher_list_workloads reads all four kit deployments 1/1 through Rancher''s k8s proxy.', '2026-07-23'),
  (7, 'Fleet GitOps + public repo + run guide', 'done', 'Published the factory to github.com/MetalRoosterSimulation/edge-proof-factory. Created a Fleet GitRepo targeting the imported cluster. Resolved a Helm-adoption ownership conflict by deleting the hand-applied namespace and force-syncing. Fleet redeployed cleanly: readyClusters 1/1, genuinely GitOps-owned. Added HOW-TO-RUN-THIS-DEMO.md.', '2026-07-23'),
  (8, 'Durable re-import', 'done', 'Fixed two re-import failure modes: added fleet.yaml with helm.takeOwnership so Fleet adopts resources a local make up already deployed, and rewrote wire-rancher.sh to detect and clean up an orphaned cluster object before re-importing. Verified end to end: tore down and rebuilt the k3d cluster, ran wire-rancher.sh once, reached 1/1 with confirmed adoption (pods kept their pre-Fleet age and gained Helm labels).', '2026-07-23'),
  (9, 'SUSE AI tier under Fleet + explain endpoint', 'done', 'Fixed a Fleet bundle-scoping failure (a GitRepo path can''t reference ../base) by making k8s/ai self-contained and additive with its own Helm release. /api/explain now returns a clear ''AI tier not reachable, run make ai'' note instead of a raw errno. Verified live: injected an rf_match_drift fault and /api/explain/etch-03 returned a real qwen2.5:0.5b explanation naming the anomaly, on-prem, no data leaving the cluster.', '2026-07-23'),
  (10, 'Factory Portal — Vercel + Supabase', 'done', 'Built a read-only Next.js 16 portal (this app) that surfaces the proof kit catalog, component maps, scale-up paths, footprint specs, and this build ledger from a dedicated Supabase Postgres project, deployed to Vercel. The k3s/Rancher demo itself is unchanged and cannot run on Vercel (serverless has no persistent cluster) — the portal is a presentation layer on top, not a replacement. Schema, seed data (transcribed from the existing handoff docs and this ledger, not invented), RLS policies, and the full test suite were built and verified against a local Supabase stack before any cloud resources were requested. Research/competitor-analysis phase was explicitly dropped from scope by user direction; the portal is being built directly. Live: Supabase project "edge-ai-demo" (ref vpdtwiyvatpwzkapvmcl, us-east-1, free tier) provisioned via the Supabase MCP server (OAuth, no token pasted anywhere); schema + seed applied and verified (zero security advisories). Initially deployed to Vercel via the deploy_to_vercel MCP tool (a one-shot file upload) at https://edge-ai-demo.vercel.app. Later upgraded to git-integrated CI: connected the Vercel project to github.com/MetalRoosterSimulation/edge-proof-factory, set NEXT_PUBLIC_SUPABASE_URL/ANON_KEY as Production+Preview env vars via `vercel env add` (CLI login is an email link, no token pasted), and pushed. First git-triggered build failed — "Couldn''t find any `pages` or `app` directory" — because the project''s Root Directory defaulted to the repo root, not `portal/`; fixed via a direct PATCH to the Vercel REST API (`rootDirectory: "portal"`) using the CLI''s own cached auth token, since neither the MCP server nor `vercel project update` exposes that setting. Next push built clean and served real Postgres data — confirmed by fetching /, /ledger, and /kits/semiconductor-predictive-maintenance directly against the new deployment ID.', '2026-07-23'),
  (11, 'The working demo ON Vercel: /demo in-browser simulation', 'done', 'Phase 10 put the documentation on Vercel; this phase put the **working demo** there. A five-agent research swarm ran first: Vercel has no always-on compute primitive (300s function cap and daily-only cron on Hobby), so a server-driven telemetry feed was rejected; nobody in the predictive-maintenance market (Augury, C3 AI, Sight Machine, Siemens, PTC — or SUSE itself) offers a no-signup, live, fault-injectable public demo, which made that exact combination the target.

Built: the kit''s whole pipeline — sensor simulator, gateway governance tier, and the SPC health model (Welford frozen baselines, clipped z-scores, Hotelling T-squared, fast/slow EWMA, least-squares RUL) — ported to TypeScript and running entirely in the visitor''s browser at [/demo](/demo). Per-visitor sandboxed fleet, fault inject/heal per tool, live governance counters (nothing leaves the tab), and an architecture x-ray mapping every on-page element to its kit tier and SUSE production counterpart.

Honesty decisions, adopted from an adversarial review before any code: the page is labeled an interactive **simulation** of the Proof Kit — it proves the model, not the SUSE stack; parity with the Python model is enforced by replaying 590 frames recorded from the real kit through the port in CI (health within 0.011, anomaly within 2e-4, RUL within 1 frame); the planned hosted-LLM explain route was cut because the kit''s explain tier is valuable precisely because it runs on-prem (Phase 9); the demo route uses no Supabase at runtime so it stays live even if this content backend sleeps; the simulation pauses while its tab is hidden because the model''s time base is frames, and a wall-clock catch-up would misrepresent it.

Verified before ship: 61/61 Vitest (including full golden parity), lint and build clean, /demo prerendered static, kit directory byte-untouched, and the production URL exercised live post-deploy.', '2026-07-23'),
  (12, 'The FULL demo on Vercel: offline buffering + AI tier', 'done', 'The demo''s audience is SUSE colleagues studying the kit to rebuild it for partners, so the whole kit experience moved onto [/demo](/demo). The gateway tier''s **offline buffering** is now live: simulate a downstream outage, watch raw frames buffer in order, restore, and watch every frame flush through the model — with a test proving outage-plus-recovery yields identical fleet state to an uninterrupted run. An egress inspector shows the exact derived JSON allowed across the governance boundary.

The kit''s **AI tier** returns as a clearly labeled hosted stand-in: per-tool Explain and a fleet-grounded Fab Assistant chat run the kit''s own prompts (the on-prem explain endpoint and the Open WebUI fleet context from Phase 9) against a hosted Claude model — accepting derived verdicts only, enforced by parsing, so raw telemetry has no path into a prompt. Without an API key the features degrade to the kit-style "answered on-prem via make ai" note. The architecture x-ray became a study map: every tier lists the exact source files (browser port and kit original) a colleague reads to rebuild it.

Verified: 82/82 tests, lint and build clean, exercised live on the production URL.', '2026-07-23');

insert into open_threads (description, status) values
  ('Additional reference kits (other use-case-library patterns) on demand via RUN.md.', 'open'),
  ('Portal is served via a one-shot Vercel file deploy (MCP deploy_to_vercel), not git-integrated CI, and has no custom domain. Recommended durable follow-up: Import Git Repository in the Vercel dashboard to connect it to github.com/MetalRoosterSimulation/edge-proof-factory (root directory portal/) so future commits auto-deploy, and add NEXT_PUBLIC_SUPABASE_URL/ANON_KEY as dashboard env vars at that point (the Vercel MCP server has no env-var API).', 'resolved'),
  ('Vercel plan for edge-ai-demo: if the account is on Hobby, partner-facing (commercial) use sits outside Hobby''s non-commercial fair-use terms — decide whether to move the project to a Pro team (~$20/mo; also lifts the 300s function and daily-cron caps).', 'open'),
  ('ANTHROPIC_API_KEY not yet set on the Vercel project — until it is added (Vercel dashboard → edge-ai-demo → Settings → Environment Variables, Production + Preview), the demo''s Explain (AI) and Fab Assistant features show the graceful "not configured" note; everything else works without it.', 'open');
